# Generated by Django 5.0.1 on 2024-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leadOwner', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('customerName', models.CharField(max_length=100)),
                ('mobileNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('leadTitle', models.CharField(max_length=100)),
                ('leadSource', models.CharField(max_length=100)),
                ('expectedDate', models.CharField(blank=True, max_length=100, null=True)),
                ('needType', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
