# Generated by Django 5.0.1 on 2024-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_leadmodel_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='status',
            field=models.CharField(default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
