# Generated by Django 5.0.1 on 2024-03-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_leadmodel_status_alter_leadmodel_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, unique=True)),
                ('customerName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
