# Generated by Django 5.0.1 on 2024-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_companymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
